{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "7703f79a-a2f8-4bef-bd63-995811ffe661",
     "showTitle": false,
     "tableResultSettingsMap": {
      "19": {
       "dataGridStateBlob": "{\"version\":1,\"tableState\":{\"columnPinning\":{\"left\":[\"#row_number#\"],\"right\":[]},\"columnSizing\":{},\"columnVisibility\":{}},\"settings\":{\"columns\":{}},\"syncTimestamp\":1774475628044}",
       "filterBlob": null,
       "queryPlanFiltersBlob": null,
       "tableResultIndex": 19
      }
     },
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "--EDA bright coffee shop \n",
    "----------------------------\n",
    "--1.Running the entire table\n",
    "SELECT *\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--2. Checking the date  range: They first collected data on 2023-01-01 and last collected data on 2023-06-30.Data duration is 6 months\n",
    "SELECT \n",
    "      MIN(transaction_date) AS Minimum_Date,\n",
    "      MAX(transaction_date) AS Maximum_Date\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--3.Checking the different store locations:3 stores namely:Lower Manhattan, Hell's Kitchen and Astoria\n",
    "SELECT DISTINCT store_location\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--4.Checking products sold at our stores: 9 distinct product types\n",
    " SELECT DISTINCT product_category\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--5.Checking product types sold at our stores : 29 different product types\n",
    " SELECT DISTINCT product_type\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--6.Checking product detail sold at our stores: 80 distinct product detail\n",
    " SELECT DISTINCT product_category\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--7. Checking FOR NULLS IN VARIOUS ROWS\n",
    "\n",
    "SELECT *\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1\n",
    "WHERE unit_price IS NULL\n",
    "OR transaction_qty IS NULL\n",
    "OR transaction_date IS NULL;\n",
    "\n",
    "--8.Checking lowest and highest unit price: lowestprice= R 0.8, highest price=R45\n",
    "SELECT MIN(unit_price) AS lowest_unit_price,\n",
    "        MAX(unit_price) AS highest_unit_price\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--9. Extracting the day and month names\n",
    "SELECT\n",
    "      transaction_date,\n",
    "      Dayname(transaction_date) AS Day_name,\n",
    "      Monthname(transaction_date) AS Month_name\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--10.Calculating the revenue\n",
    "SELECT unit_price,\n",
    "      transaction_qty,\n",
    "      unit_price*transaction_qty AS Revenue\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;\n",
    "\n",
    "--11. Combining functions to get a clean and enhanced data set\n",
    "\n",
    "SELECT transaction_id,\n",
    "       transaction_date,\n",
    "       transaction_time,\n",
    "       transaction_qty,\n",
    "       store_id,\n",
    "       store_location,\n",
    "       product_id,\n",
    "       unit_price,\n",
    "       product_category,\n",
    "       product_type,\n",
    "       product_detail,\n",
    "--Adding columns to enhance the table for better insights\n",
    "--Column 1\n",
    "       Dayname(transaction_date) AS Day_name, \n",
    "--Column 2\n",
    "       Monthname(transaction_date) AS Month_name,\n",
    "--Column 3\n",
    "       Dayofmonth(transaction_date) AS Date_of_month,\n",
    "\n",
    "--Column 4-Determining weekday/weekend\n",
    "  CASE WHEN Dayname(transaction_date) in ('Sun', 'Sat') THEN 'Weekend'\n",
    "  ELSE 'Weekday'\n",
    "  End AS Day_classiffication, \n",
    " --Column 5- Time buckets\n",
    "  CASE \n",
    "      WHEN date_format(transaction_time,'HH:mm:ss') BETWEEN '05:00:00' AND '08:59:59' THEN '01.Rush Hour'\n",
    "      WHEN date_format(transaction_time,'HH:mm:ss') BETWEEN '09:00:00' AND '11:59:59' THEN '02.Mid Morning'\n",
    "      WHEN date_format(transaction_time,'HH:mm:ss') BETWEEN '12:00:00' AND '15:59:59' THEN '03.Afternoon'\n",
    "      WHEN date_format(transaction_time,'HH:mm:ss') BETWEEN '16:00:00' AND '18:00:00' THEN '04.Rush Hour'\n",
    "      ELSE '05.Night'\n",
    "END AS Time_classification,\n",
    "\n",
    "--Column 6-Spend buckets\n",
    "CASE\n",
    "      WHEN (transaction_qty*unit_price) <=50 THEN '01.Low Spender'\n",
    "      WHEN (transaction_qty*unit_price) BETWEEN 51 AND 200 THEN '02.Medium Spender'     \n",
    "      WHEN (transaction_qty*unit_price) BETWEEN 201 AND 300 THEN '03. Moreki'\n",
    "      ELSE '04.Blesser'\n",
    "END AS Spend_bucket,\n",
    "\n",
    "--Column 8- Revenue\n",
    "transaction_qty*unit_price AS Revenue\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis;\n",
    "\n",
    "      \n",
    "\n",
    "-----------------------------------------------------------\n",
    "--12.AGGREGATIONS\n",
    "SELECT COUNT(*) AS number_of_rows, \n",
    "       COUNT(DISTINCT transaction_id) AS number_of_sales,\n",
    "       COUNT(DISTINCT store_id) AS number_of_stores\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;  \n",
    "-------------------------------------------------------------\n",
    "SELECT transaction_id,\n",
    "       transaction_date,\n",
    "       Dayname(transaction_date)  AS Day_name,\n",
    "       Monthname(transaction_date) AS Month_name,\n",
    "       transaction_qty*unit_price AS revenue_per_tnx\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;     \n",
    "SELECT transaction_id,\n",
    "       transaction_date,\n",
    "       Dayname(transaction_date)  AS Day_name,\n",
    "       Monthname(transaction_date) AS Month_name,\n",
    "       transaction_qty*unit_price AS revenue_per_tnx\n",
    "FROM `consultation-class`.default.bright_coffee_shop_analysis_case_study_1;     \n",
    "----------------------------------------------------------------------  \n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "default"
    }
   },
   "notebookName": "bright_coffee_shop_analysis_case_study.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
